routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::pattern('id', '[0-9]+');


Auth::routes();
Route::any('register', function(){ abort(404); });
Route::get('logout', function(){ return redirect()->to('/'); });


Route::get('notify_webinar', 'CronController@webinar');
Route::get('/', 'PageController@index')->name('index');
Route::get('events', 'EventController@events')->name('events');
Route::get('event/{id}', 'EventController@event')->name('event');
Route::get('lections', 'LectionController@lections')->name('lections');
Route::get('lection/{id}', 'LectionController@lection')->name('lection');
Route::get('about', 'PageController@about')->name('about');
Route::any('forms', 'PageController@forms')->name('forms');
Route::any('email_notify', 'PageController@email_notify')->name('email_notify');
Route::any('check_notify', 'PageController@check_notify')->name('check_notify');
Route::any('notify_birthday', 'CronController@notify_birthday')->name('notify_birthday');
Route::any('check_webinars_stat/{id}', 'CronController@check_webinars_stat')->name('check_webinars_stat');


// Admin
Route::group(['middleware' => 'auth', 'prefix' => 'admin'], function(){
	Route::get('users', 'AdminController@users')->name('admin.users');
	Route::any('user/edit/{id}', 'AdminController@useredit')->name('admin.user.edit');
	Route::get('user/delete/{id}', 'AdminController@userdelete')->name('admin.user.delete');
	Route::any('user/add', 'AdminController@useradd')->name('admin.user.add');
	Route::any('users/import', 'AdminController@import')->name('admin.users.import');
	Route::any('users/export', 'AdminController@export')->name('admin.users.export');
	Route::any('users/notify', 'AdminController@notify')->name('admin.users.notify');
	Route::any('users/addscore/{id?}', 'AdminController@addscore')->name('admin.users.addscore');
	Route::any('users/search', 'AdminController@usersearch')->name('admin.users.search');
	Route::get('webinars', 'AdminController@webinars')->name('admin.webinars');
	Route::any('webinar/{id?}', 'AdminController@webinar')->name('admin.webinar');
	Route::get('webinar/delete/{id}', 'AdminController@webinardelete')->name('admin.webinar.delete');
	Route::get('works', 'AdminController@works')->name('admin.works');
	Route::any('work/{id?}', 'AdminController@work')->name('admin.work');
	Route::get('work/delete/{id}', 'AdminController@workdelete')->name('admin.work.delete');
	Route::get('contests', 'AdminController@contests')->name('admin.contests');
	Route::any('contest/{id?}', 'AdminController@contest')->name('admin.contest');
	Route::any('contests/buyed', 'AdminController@buyed')->name('admin.contests.buyed');
	Route::get('contest/delete/{id}', 'AdminController@contestdelete')->name('admin.contest.delete');
	Route::get('contests/buyed/export', 'AdminController@export')->name('admin.export');
	Route::get('events', 'AdminController@events')->name('admin.events');
	Route::any('event/{id?}', 'AdminController@event')->name('admin.event');
	Route::get('event/delete/{id}', 'AdminController@eventdelete')->name('admin.event.delete');
	Route::get('lections', 'AdminController@lections')->name('admin.lections');
	Route::any('lection/{id?}', 'AdminController@lection')->name('admin.lection');
	Route::get('lection/delete/{id}', 'AdminController@lectiondelete')->name('admin.lection.delete');
	Route::post('contest/buyset', 'AdminController@buyset')->name('admin.buy.set');
	Route::any('about', 'AdminController@about')->name('admin.about');
	Route::post('upload_img', 'PageController@upload_img');
	Route::get('banners', 'AdminController@banners')->name('admin.banners');
	Route::any('banner/{id?}', 'AdminController@banner')->name('admin.banner');
	Route::get('banner/delete/{id}', 'AdminController@bannerdelete')->name('admin.banner.delete');
	Route::get('medals', 'AdminController@medals')->name('admin.medals');
	Route::any('medal/{id?}', 'AdminController@medal')->name('admin.medal');
	Route::get('medal/delete/{id}', 'AdminController@medaldelete')->name('admin.medal.delete');
	Route::get('medal/set', 'AdminController@getMedalSet')->name('admin.medal.set');
	Route::post('medal/set', 'AdminController@postMedalSet');
	Route::post('medal/unset', 'AdminController@postMedalUnset');
	Route::post('medal/search', 'AdminController@search_medal')->name('admin.search_medal');
	Route::post('eventgallery', 'AdminController@eventgallery')->name('admin.eventgallery');
});

// API
Route::group(['prefix' => 'api'], function(){
	Route::get('friends/{id}', 'ApiController@friends')->name('api.friends');
	Route::get('users', 'ApiController@users')->name('api.users');
	Route::any('auth', 'ApiController@auth');
	Route::any('dialogs', 'ApiController@dialogs');
	Route::any('unread_dialogs', 'ApiController@unread_dialogs');
	Route::any('messages', 'ApiController@messages');
	Route::any('message_send', 'ApiController@message_send');
	Route::any('works', 'ApiController@works');
	Route::any('histories', 'ApiController@histories');
});

// Auth
Route::group(['middleware' => 'auth'], function(){
	Route::get('user/edit', 'UserController@edit')->name('user.edit');
	Route::post('user/edit', 'UserController@save');
	Route::any('messenger/{id?}', 'UserController@messenger')->name('messenger');
	Route::any('messenger/{id}/new', 'UserController@messenger_newpost')->name('messenger.new');
	Route::any('messenger/newcount', 'UserController@messenger_newpost_count')->name('messenger.newcount');
	Route::get('notify/{id}', 'NotifyController@index')->name('notify');
	Route::post('work/{id}', 'WorkController@answer');
	Route::post('answer/{id}', 'WorkController@score')->name('answer');
	Route::post('answer/cancel/{id}', 'WorkController@cancel')->name('answer.cancel');
	Route::get('buy/{id}', 'ContestController@buy')->name('buy');
	Route::any('user/{id}', 'UserController@user')->name('user');
	Route::get('webinars', 'WebinarController@webinars')->name('webinars');
	Route::get('webinar/{id}', 'WebinarController@webinar')->name('webinar');
	Route::get('work', 'WorkController@index')->name('works');
	Route::get('work/{id}', 'WorkController@work')->name('work');
	Route::get('heroes', 'HeroesController@heroes')->name('heroes');
	Route::get('contests', 'ContestController@index')->name('contests');
	Route::get('wishlist', 'WishlistController@index')->name('wishlist');
	Route::get('wishlist/add/{id}', 'WishlistController@add')->name('wishlist.add');
	Route::get('wishlist/delete/{id}', 'WishlistController@delete')->name('wishlist.delete');
	Route::any('search_friends/{id}/{all?}', 'UserController@search_friends')->name('search_friends')->where('all', 'all');
	Route::any('clearnotifies', 'UserController@clearnotifies')->name('clearnotifies');
	Route::any('wsid', 'UserController@wsid')->name('wsid');
	Route::get('webinar/stats/{id}', 'WebinarController@stats')->name('webinar.stats');
	Route::get('webinar/stats/{id}/user/{uid}', 'WebinarController@stats_user')->name('webinar.stats.user')->where('uid', '[0-9]+');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Gerardojbaez\Messenger\Contracts\MessageableInterface;
use Gerardojbaez\Messenger\Traits\Messageable;

class User extends Authenticatable implements MessageableInterface
{
    use Notifiable;
    use Messageable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'id', 'name', 'email', 'password', 'uid', 'bday', 'login', 'pass', 'token', 'agency', 'status', 'intro', 'score', 'sex', 'lastname', 'firstname', 'hobby', 'achive', 'nick', 'visited_at', 'email', 'ws_id', 'webinar_aid'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function roles()
    {
        return $this->belongsToMany('App\Role');
    }

    public function hasRole($name)
    {
        return (bool)($this->role == $name);
    }

    public function getBdayAttribute($v)
    {
        return \Carbon\Carbon::createFromTimestamp($v)->format('d.m.Y'); //toDateTimeString();
    }

    public function setBdayAttribute($v)
    {
        if(empty($v))
            return '';

        if(is_numeric($v))
            $this->attributes['bday'] = $v;
        else
        {
            list($day,$month,$year) = explode('.', $v);
            $this->attributes['bday'] = \Carbon\Carbon::createFromDate($year, $month, $day)->timestamp;
        }
    }

    public function getCoverAttribute($v)
    {
        return \Storage::has('/img/covers/'.$this->id.'.jpg') ? '/img/covers/'.$this->id.'.jpg?'.mt_rand(0,100000) : '/img/covers/0.jpg';
    }

    public function getRoleAttribute()
    {
        return @$this->roles()->first()->title;
    }

    public function getBadgeAttribute()
    {
        $out = new \stdClass;

        switch(true)
        {
            case $this->score < 500 || $this->score == 0:
                $out->icon = '/img/badges/top_new.png';
                $out->text = 'Новичок';
            break;
            case $this->score < 1000:
                $out->icon = '/img/badges/top1.png';
                $out->text = 'Ученик';
            break;
            case $this->score < 2000:
                $out->icon = '/img/badges/top2.png';
                $out->text = 'Студент';
            break;
            default:
                $out->icon = '/img/badges/top3.png';
                $out->text = 'Бакалавр';
        }

        return $out;
    }

    public function getNickAttribute($v)
    {
        return !$v ? 'user-'.$this->id : $v;
    }

    public function getAvatarAttribute()
    {
        return !\Storage::has('img/avatars/'.$this->id.'.jpg') || (auth()->check() && $this->g_user_role == 'moderator' && $this->g_user_role == 'user') ? 'img/avatars/0'.$this->sex.'.jpg' : 'img/avatars/'.$this->id.'.jpg?'.mt_rand(0,100000);
    }

    public function friends()
    {
        return $this->belongsToMany('App\User', 'friends', 'user_id', 'friend_id');
    }

    public function friendlies()
    {
        return $this->belongsToMany('App\User', 'friends', 'friend_id', 'user_id');
    }

    public function isFriend()
    {
        return (bool)auth()->user()->friends()->where('users.id', $this->id)->count();
    }

    public function notifies()
    {
        return $this->hasMany('App\Notify');
    }

    public function answers()
    {
        return $this->hasMany('App\Answer');
    }

    public function hasAnswer($id)
    {
        return $this->answers()->where('work_id', $id)->whereIn('scored', ['0','1'])->count();
    }

    public function addscore($score)
    {
        $score = $this->score + $score;
        $this->update(['score' => $score]);
    }

    public function delscore($score)
    {
        $score = $this->score - $score;
        $this->update(['score' => $score]);
    }

    public function contests()
    {
        return $this->belongsToMany('App\Contest')->withTimestamps();
    }

    public function wishlist()
    {
        return $this->belongsToMany('App\Contest', 'wishlists', 'user_id', 'contest_id');
    }

    public function histories()
    {
        return $this->hasMany('App\History');
    }

    public function medals()
    {
        return $this->belongsToMany('App\Medal');
    }

    public function mywebinars()
    {
        return $this->belongsToMany('App\Webinar', 'members_webinar', 'user_id', 'webinar_id');
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
{{ app('captcha')->multiple() }}
@if(auth()->check())
    <?php auth()->user()->update(['visited_at' => time()]) ?>
@endif
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <base href="{{ config('app.url') }}">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="wsserver" content="{{ env('WS_SERVER') }}">

    <title>{{ @$pagetitle ?: 'Страница не найдена' }} — {{ config('app.name') }}</title>

    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet">
    <link href="css/plugins/jasny/jasny-bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.25/jquery.fancybox.min.css">

    <!-- Toastr style -->
    <link href="css/plugins/toastr/toastr.min.css" rel="stylesheet">
    
    <link href="css/plugins/datapicker/datepicker3.css" rel="stylesheet">
    
    <!-- Sweet Alert -->
    <link href="css/plugins/sweetalert/sweetalert.css" rel="stylesheet">

    <!-- Gritter -->
    <link href="js/plugins/gritter/jquery.gritter.css" rel="stylesheet">

    <!-- Ladda style -->
    <link href="css/plugins/ladda/ladda-themeless.min.css" rel="stylesheet">

    <link href="css/animate.css" rel="stylesheet">
    <link href="css/style.css?4" rel="stylesheet">

    <link href="css/plugins/slick/slick.css" rel="stylesheet">
    <link href="css/plugins/slick/slick-theme.css" rel="stylesheet">


    <link href="css/dropzone.css" rel="stylesheet">

    <!-- Cookie -->
    <script src="js/js.cookie.js"></script>

    <!-- Mainly scripts -->
    <!-- <script src="js/jquery-3.1.1.min.js"></script> -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="js/bootstrap.min.js?1"></script>
    <script src="js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.25/jquery.fancybox.min.js"></script>

    <!-- Socket.io -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.3/socket.io.js"></script>
    @if(auth()->check())
    <script>
        var socket = io(':3000', {
            // origins: '{{ env('APP_URL') }}:*',
            query: 'id={{ auth()->id() }}@if(@$webinar)&webinarid={{ $webinar->id }}@endif'
        });
    </script>
    @endif

    <!-- slick carousel-->
    <script src="js/plugins/slick/slick.min.js"></script>

    <!-- Typehead -->
    <script src="js/plugins/typehead/bootstrap3-typeahead.min.js"></script>

    <!-- Flot -->
    <script src="js/plugins/flot/jquery.flot.js"></script>
    <script src="js/plugins/flot/jquery.flot.tooltip.min.js"></script>
    <script src="js/plugins/flot/jquery.flot.spline.js"></script>
    <script src="js/plugins/flot/jquery.flot.resize.js"></script>
    <script src="js/plugins/flot/jquery.flot.pie.js"></script>

    <!-- Peity -->
    <script src="js/plugins/peity/jquery.peity.min.js"></script>
    <script src="js/demo/peity-demo.js"></script>
    
    <!-- Sweet alert -->
    <script src="js/plugins/sweetalert/sweetalert.min.js"></script>

    <!-- DROPZONE -->
    <script src="js/plugins/dropzone/dropzone.js"></script>

    <script src="js/jQuery.paginate.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="js/inspinia.js"></script>
    <script src="js/plugins/pace/pace.min.js"></script>
    <script src="js/main.js?2"></script>

    <!-- jQuery UI -->
    <script src="js/plugins/jquery-ui/jquery-ui.min.js"></script>

    <!-- Ladda -->
    <script src="js/plugins/ladda/spin.min.js"></script>
    <script src="js/plugins/ladda/ladda.min.js"></script>
    <script src="js/plugins/ladda/ladda.jquery.min.js"></script>

    <!-- Jasny -->
    <script src="js/plugins/jasny/jasny-bootstrap.min.js"></script>

    <!-- GITTER -->
    <script src="js/plugins/gritter/jquery.gritter.min.js"></script>

    <!-- Sparkline -->
    <script src="js/plugins/sparkline/jquery.sparkline.min.js"></script>

    <!-- Sparkline demo data  -->
    <script src="js/demo/sparkline-demo.js"></script>

    <!-- Data picker -->
    <script src="js/plugins/datapicker/bootstrap-datepicker.js"></script>

    <!-- Toastr -->
    <script src="js/plugins/toastr/toastr.min.js"></script>
    
    <script src="/js/jquery.form.min.js"></script>

    <link rel="stylesheet" type="text/css" href="/js/reformator/reformator.css" />
    
    @stack('js')

</head>

<body class="@if(@$_COOKIE['mini-sidebar']) mini-navbar @endif pace-done ">
    <div id="wrapper">
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu text-center" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element"> <span>
                            <a href="/contests"><img alt="image" src="http://placehold.it/80x80"></a>
                             </span>
                        </div>
                        <div class="logo-element">
                            <img alt="image" src="http://placehold.it/40x40">
                        </div>
                    </li>
                    @if(auth()->check() && ($g_user_role == 'admin' || $g_user_role == 'superadmin'))
                        <li>
                            <a href="#"><i class="fa fa-2x fa-lock"></i><br><span class="nav-label">Админка</span><span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level collapse">
                                <li class="{{ request()->route() && request()->route()->getName() == 'admin.contests' ? 'active' : '' }}"><a href="{{ route('admin.contests') }}">Товары</a></li>
                            </ul>
                        </li>
                    @endif

                    @if(auth()->check())
                        <li class="{{ request()->route() && request()->route()->getName() == 'contests' ? 'active' : '' }}">
                            <a href="{{ route('contests') }}" title="Призы"><i class="fa fa-2x fa-star-o"></i><br><span class="nav-label">Призы</span></a>
                        </li>

                    @endif
                </ul>

            </div>
        </nav>

        <div id="page-wrapper" class="gray-bg dashbard-1">
        <div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="javascript:;"><i class="fa fa-bars"></i> </a>
            </div>
                <ul class="nav navbar-top-links pull-right">				
					@if(auth()->check())
                        <li><a>{{ (integer)auth()->user()->score }} {{ trans_choice('рубль|рубля|рублей', (integer)auth()->user()->score) }}</a></li>
                        <li class="dropdown">
                            <a class="count-info" href="{{ route('wishlist') }}">
                                @php $g_wishlist_count = auth()->user()->wishlist()->count(); @endphp
                                <i class="fa fa-heart-o"></i>  @if((bool)$g_wishlist_count) <span class="label label-primary">{{ $g_wishlist_count }}</span> @endif
                            </a>
                        </li>
                    @endif
                    
                    @if (Auth::guest())
                        <li><a href="{{ route('login') }}"><i class="fa fa-sign-in"></i> Войти</a></li>
                    @else
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><img src="{{ auth()->user()->avatar }}" alt="" class="nav-avatar img-circle circle-border avatar-{{ auth()->user()->id }}"> <span class="hidden-xs">{{ auth()->user()->name }}</span> <span class="caret"></span></a>
                          <ul class="dropdown-menu">
                            <li>
                                <a href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                             document.getElementById('logout-form').submit();">
                                    <i class="fa fa-sign-out"></i> Выйти
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                          </ul>
                        </li>
                    @endif
                </ul>

            </nav>
        </div>
        @yield('header')

        <div class="wrapper wrapper-content animated fadeInDown">
            @yield('content')
        </div>

        </div>
    </div>
</body>
</html>